name: Push

on:
  pull_request:
  workflow_dispatch:

jobs:
# Alterar o build quando terminar o dockerfile
  build:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout do código-fonte
        uses: actions/checkout@v2

      - name: Configurar o ambiente Java
        uses: actions/setup-java@v2.4.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Fazer o build
        run: |
          cd post-microsservice && ./gradlew build
